version: '3.8'

services:
  bugtracker:
    build: ./BugTracker
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=bugtrackingdb;User=root;Password=password;
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bugtrackingdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - UPLOAD_LIMIT=300M
      - MYSQL_ROOT_PASSWORD=password
      - PMA_ABSOLUTE_URI=http://localhost:8080/
      - PMA_DISABLE_SSL_VERIFICATION=true
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: